name: Example workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Modules
      - run: yarn

      - name: Run tests
      - run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittest
          name: codecov-1
